name: github-app
on: 
   push:

   pullrequest:
      branches:
        -master
    
jobs:
 build:
  name: Build
  runs-on: ubuntu-latest

  steps: 
     -name: Checkout code
      uses: actions/checkout@v3
     -name: Install Node 16
      uses: actions/setup-node@v3
      with:
         node-version: 16.x 
     -name: Install dependencies
      run: npm i
     -name: build project
      run: npm run build
     -name: Upload artifact in order to deploy
      uses: action/upload-artifact@v2
      with: 
        name: production-files
        path: ./build

  deploy:
    name: deploy
    runsOn: ubuntu-latest
    needs: build
    steps: 
     -name: Download artifact
      uses: actions/download-artifact@v2
      with:
         name: production-files
         path: ./build

     -name: Deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
         github_token: ${{secret.GITSTAR}}
         publish_dir: ./build

      
